// visible
export const ADD_WEBSITE_VISIBLE = 'ADD_WEBSITE_VISIBLE'
export const CONFIG_INFO_VISIBLE = 'CONFIG_INFO_VISIBLE'
export const ALIAS_BIDN_VISIBLE = 'ALIAS_BIDN_VISIBLE'
export const CLICK_CERTIFY_VISIBLE = 'CLICK_CERTIFY_VISIBLE'
export const WEBSITE_NOTE_VISIBLE = 'WEBSITE_NOTE_VISIBLE'
export const CREATED_SUBSTITUTE_VISIBLE = 'CREATED_SUBSTITUTE_VISIBLE'
// refresh
export const ALWAYS_ONLINE_REFRESH = 'ALWAYS_ONLINE_REFRESH'

export const WEBSITE = 'WEBSITE'
export const RECEIVE_WEBSITE_BY_DOMAIN = 'RECEIVE_WEBSITE_BY_DOMAIN'
export const WEBSITE_ADDED = 'WEBSITE_ADDED'
