export const RECEIVE_MONITOR_BY_PAGE = 'RECEIVE_MONITOR_BY_PAGE'
export const RECEIVE_MONITOR_TOTAL = 'RECEIVE_MONITOR_TOTAL'
/**/
export const ADD_MONITOR_SAVE = 'ADD_MONITOR_SAVE'
export const PAUSE_MONITOR_LIST = 'PAUSE_MONITOR_LIST'
export const OPEN_MONITOR_LIST = 'OPEN_MONITOR_LIST'
export const DELETE_MONITOR_LIST = 'DELETE_MONITOR_LIST'
/*弹框*/
export const ADD_MONITOR_VISIBLE = 'ADD_MONITOR_VISIBLE'
export const LINKAGE_SETTING_VISIBLE = 'LINKAGE_SETTING_VISIBLE'
export const TASK_CONFIG_VISIBLE = 'TASK_CONFIG_VISIBLE'
export const ALARM_SETTING_VISIBLE = 'ALARM_SETTING_VISIBLE'
